### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Freeaqingme** [senghoo/modsecurity-go#1]
Hi,

I'd like to use this project for a project of mine, but I noticed there's no license mentioned. Could you perhaps provide under which license the code in this project licensed? For example by [adding a license file](https://help.github.com/articles/adding-a-license-to-a-repository/)?

Personally I'd prefer the apache license or an MIT/BSD-clause license, but that's of course entirely up to you. https://choosealicense.com/

Thanks!

**Comment by senghoo** [comment]
I just added license. It use mit license. 

I am glad that this project will help you solve your problem. But this project is not working now.  Because when i write this project, libmodsecurity seems not working well.  

If libmodsecurity becomes working well please tell me, I will continue to working on this project again.

**Comment by thibolepilote** [comment]
Hi, 

I'd like to use modsecurity in a go programm, but I didn't find any working solution...
Your code seems like it could help me, but unfortunately the Libmodsecurity dependency isn't existing anymore... Do you have any solution?

Thk you
